apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-app
spec:
  selector:
    matchLabels:
      app: mysql-app
  template:
    metadata:
      labels:
        app: mysql-app
    spec:
      containers:
      - name: mysql
        imagePullPolicy: IfNotPresent
        image: dprakash001/fitness-db
        env:
          - name:  MYSQL_ROOT_PASSWORD
            valueFrom:
              secretKeyRef:
                name:  mysql-secret
                key:  dbpassword
          - name: MYSQL_USER
            value: db_user
          - name: MYSQL_PASSWORD
            value: .mypwd
        args: ["--default-authentication-plugin=mysql_native_password"]
        ports:
        - containerPort: 3306
